// apic_version = 0.6.1
#import "PTModel.h"
#import <Foundation/Foundation.h>
NS_ASSUME_NONNULL_BEGIN
typedef NS_ENUM(NSUInteger, PTErrorCodeEnum){
    UNKNOWN_ERROR = 0,
    USER_NOT_EXIST = 1000,
    USER_NOT_ACTIVE = 1001,
    REQUEST_EMPTY = 1007,
    CREATE_USER_ERROR = 1010,
    SIGNATURE_ERROR = 1011,
    SOURCE_OR_TARGET_ID_EMPTY = 1014,
    PARAM_NOT_VALID = 1015,
    RECIPE_NOT_EXIST = 1017,
    USER_ABNORMAL = 1019,
    NOT_ALL_PARAMETERS_PROVIDED = 1020,
    PROTO_OPERATION_IS_NOT_ALLOWED = 1031,
    PROTO_EVENT_NOT_EXIST = 1038,
    CAN_NOT_FOLLOW_SELF = 1040,
    PROTO_CREATE_REPORT_ERROR = 1041,
    SEND_VERIFICATION_EXCEED_PHONE_LIMIT = 1084,
    SEND_VERIFICATION_NOT_COOL_DOWN = 1085,
    SMS_VERIFY_FAILED = 1086,
    USER_ALREADY_BIND_PHONE = 1087,
    PHONE_ALREADY_BOUND = 1088,
    SEND_VERIFICATION_CODE_FAILED = 1089,
    USER_NOT_BIND_PHONE = 1090,
    ALREADY_BOUND_BY_OTHER_ACCOUNT = 1091,
    SEND_VERIFICATION_EXCEED_USER_LIMIT = 1097,
    PROTO_QUESTION_NOT_EXIST = 1122,
    PROTO_USER_FORBID_SPEAK = 1140,
    REQUEST_WECHAT_USER_ERROR = 1141,
    VENICE_INTERNAL_SERVER_ERROR = 1145,
    VENICE_API_ERROR = 1151,
    FOLLOW_USER_NUMBER_EXCEEDED = 1158,
    PROTO_CONTAIN_FORBIDDEN_WORDS = 1166,
    FOLLOW_USER_FREQUENCY_TOO_HIGH = 1170,
    LOGIN_REQUIRED = 1177,
    SESSION_EXPIRED = 1178,
    AUTHORIZATION_CODE_INVALID = 1210,
    OAUTH_VALIDATE_FAILED = 1211,
    ADRESS_BOOK_IS_TOO_BIG = 1300,
    ESSAY_NOT_EXIST = 1400,
    FORBID_DELETE_COMMENT = 1401,
    DEVICE_ID_INVALID = 1402,
    THEME_NOT_EXIST = 1403,
    FORBID_UPDATE_ESSAY = 1404,
    INTERESTED_TAG_MUST_OVER_2 = 1411,
    DISH_NOT_EXIST = 1501,
    FORBID_UPDATE_DISH = 1502,
    QUESTIONNAIRE_NOT_EXIST = 1503,
    WELFARE_NOT_EXIST = 1504,
    USER_WELFARE_NOT_EXISTS = 1505,
    PKX_FEATURE_INVALID = 1601,
    EXPERIMENT_ERROR = 1700,
    CHUCODE_NOT_VALID = 1800,
    EQUIPMENT_CATEGORY_ALREADY_EXIST = 1810,
    EQUIPMENT_BRAND_ALREADY_EXIST = 1811,
    EQUIPMENT_CATEGORY_ERROR = 1812,
    EQUIPMENT_BRAND_ERROR = 1813,
};
@interface PTErrorCodeMessage : PTModel
/**
 当发生业务错误时,返回的错误信息
 */
@property (nonatomic, copy) NSString *message;
/**
 当发生业务错误时,返回的错误Code
 */
@property (nonatomic, assign) PTErrorCodeEnum code;
- (instancetype)initWithMessage:(NSString *)message
                           code:(PTErrorCodeEnum)code;
@end
NS_ASSUME_NONNULL_END
